language: node_js
node_js:
  - "0.12"
  - "4.0"

install:
  - npm install istanbul
  - npm install -g standard
  - npm install -g snazzy
  - npm install -g pm2
  - export COVERALLS_SERVICE_NAME=travis-ci
  - make setup

script:
  - make tests
  # - make standard  # checks JS standard

# send coverage report to coveralls.io
after_success:
  - make coveralls

# email notifications
notifications:
    email: false
